travis:
  secure:
    BINSTAR_TOKEN: ApRYeHGixXdkh464vLGBQ7Qay1cFPZwS9IYR0lC77zpUucLbIWU/rOi6LuVMpsxMyvYVmhS75jlra2AtPbzyMcQf+jyniYthppA0PYAx9snRk89JvZjgW2oNCaUD9KIh7NPe9PFtKVjExxHvtaflMPhDiLmbbno3nJSc5VnJviOWi+z+JNr5qf2MlLDsznIkCjealC/VDyWONynXcAmBDq2FUfld5qvznogJC7CEJp4ZzZKbOlnKw6bUXUo5qZF/GA4Kc/9gP+PoxHWv2YvoyWbz3ANfC7abmNGRwhaU81S6NUk+wKtmot/EpPZosl9CU9Sj5d4cXixQ8vJy8gywyb8avfPOcN+FBV7T8oGBhlNYWcaLs28TYfZ1tF0FZMw8DOjzoPQLw73dxU3AhZuHkSTsQu0AVcJr8N7CbMEIrqZ5bIj6oNyVoUjz+G/o5njbKuO4J9vSekD7ZFmBYv5hTGS5sM9gg0EeBF7ygHYrbYtKxfsIxqWg2oGf4eXTE8IPKuL8eMklRZMzKg1TUfOnVVhhHgG/hTWcUQcaAe6eIrSzDfeuGdOJ8zF5Fffnsw00PyDPXEQWH9ndx7tUTuZ8HfIVSxA+/Gp7Z+aY/d9m3CXs/vWEsppTQbXhVXSGBMwA+jE60f5+SC9xw0SxfHE8IHHjDQXudyUB0jm2xLCNOBE=
conda_forge_output_validation: true
bot:
  automerge: true
